# Generated by Django 5.1.4 on 2025-01-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team_alter_users_team_delete_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
