# Generated by Django 5.1.4 on 2025-01-11 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_team_points_alter_team_rank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('Web', 'Web Exploitation'), ('Reverse', 'Reverse Engineering'), ('Crypto', 'Cryptography'), ('Forensics', 'Digital Forensics'), ('PWN', 'Binary Exploitation'), ('OSINT', 'OSINT')], max_length=255),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='subcategory',
            field=models.CharField(choices=[('RSA', 'RSA'), ('XSS', 'XSS'), ('Dynamic', 'Dynamic')], max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
