# Generated by Django 5.1.4 on 2025-01-12 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_team_mambers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='mambers',
            new_name='members',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='api.team'),
        ),
    ]
