# Generated by Django 5.1.4 on 2025-01-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_mambers_team_members_remove_team_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
