# Generated by Django 5.1.4 on 2025-03-12 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_team_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.TextField(default='No description provided.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='flag',
            field=models.CharField(default='No description provided.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='point',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('Web', 'Web Exploitation'), ('Reverse', 'Reverse Engineering'), ('Crypto', 'Cryptography'), ('Forensics', 'Digital Forensics'), ('PWN', 'Binary Exploitation'), ('OSINT', 'OSINT'), ('Miscellaneous', 'Miscellaneous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='subcategory',
            field=models.CharField(choices=[('RSA', 'RSA'), ('SQL Injection', 'SQL Injection'), ('Memory Forensics', 'Memory Forensics'), ('XSS', 'Cross-Site Scripting (XSS)'), ('Steganography', 'Steganography')], max_length=50),
        ),
        migrations.CreateModel(
            name='SolvedChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'challenge'), name='unique_solved_challenge')],
            },
        ),
        migrations.CreateModel(
            name='SolvedChallenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
