# Generated by Django 5.1.4 on 2025-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_challenge_description_challenge_flag_challenge_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='flag',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('Web', 'Web Exploitation'), ('Reverse', 'Reverse Engineering'), ('Crypto', 'Cryptography'), ('Forensics', 'Digital Forensics'), ('PWN', 'Binary Exploitation'), ('OSINT', 'OSINT'), ('Miscellaneous', 'Miscellaneous')], max_length=255),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=255),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='point',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='subcategory',
            field=models.CharField(choices=[('RSA', 'RSA'), ('SQL Injection', 'SQL Injection'), ('Memory Forensics', 'Memory Forensics'), ('XSS', 'XSS'), ('Steganography', 'Steganography'), ('Dynamic', 'Dynamic')], max_length=255),
        ),
    ]
