# Generated by Django 5.1.4 on 2025-03-12 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_challenge_flag_alter_challenge_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='solvedchallenge',
            name='unique_solved_challenge',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='point',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('Web', 'Web Exploitation'), ('Reverse', 'Reverse Engineering'), ('Crypto', 'Cryptography'), ('Forensics', 'Digital Forensics'), ('PWN', 'Binary Exploitation'), ('OSINT', 'OSINT'), ('Miscllaneous', 'Miscllaneous')], max_length=255),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='creator',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='solvedchallenge',
            unique_together={('user', 'challenge')},
        ),
    ]
