# Generated by Django 5.1.4 on 2025-03-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_solvedchallenge_unique_solved_challenge_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolvedChallenge',
        ),
    ]
