# Generated by Django 5.1.4 on 2025-03-12 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_solvedchallenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='created_at',
        ),
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='flag',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='point',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='subcategory',
            field=models.CharField(max_length=255),
        ),
    ]
