# Generated by Django 5.1.4 on 2025-03-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_category_challenge_title_and_more'),
    ]

    operations = [
    ]
