# Generated by Django 5.1.7 on 2025-03-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_challenge_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='flag',
            field=models.CharField(max_length=255),
        ),
    ]
