# Generated by Django 5.1.7 on 2025-03-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_challenge_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
