# Generated by Django 5.1.4 on 2025-04-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_learningmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmaterial',
            name='link',
        ),
    ]
