# Generated by Django 5.1.4 on 2025-04-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_solvedassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedassessment',
            name='score',
            field=models.IntegerField(),
        ),
    ]
