# Generated by Django 5.1.4 on 2025-04-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_solvedassessment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
