# Generated by Django 5.1.4 on 2025-04-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_learningmaterial_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmaterial',
            name='content',
        ),
    ]
