# Generated by Django 5.1.4 on 2025-04-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_learningmaterial_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
