# Generated by Django 5.1.4 on 2025-04-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_learningmaterial_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solvedassessment',
            name='submitted_at',
        ),
    ]
