# Generated by Django 5.1.4 on 2025-04-26 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_solvedassessment_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedassessment',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solvedassessment',
            name='total_questions',
            field=models.IntegerField(default=1),
        ),
    ]
